// Export all API services
export { AuthService } from "./auth.service"
export { careService } from "./care"
export { homecategoriesService } from "./homecategories"
export { usersService } from "./users"
export { categoriesService } from "./categories"
export { brandsService } from "./brands"
export { productsService } from "./products"
export { ordersService } from "./orders"
export { warrantyService } from "./warranty"
export { giveawaysService } from "./giveaways"
export { policiesService } from "./policies"
export { faqsService } from "./faqs"
export { reviewsService } from "./reviews"
export { loyaltyService } from "./loyalty"
export { seoService } from "./seo"
export { marketingService } from "./marketing"
export { flashsellService } from "./flashsell"
export { adminService } from "./admin"

// Export types
export type * from "../types"
