import type { Product, Category, Brand } from "../types"

export const mockBrands: Brand[] = [
  { id: "1", name: "Apple", slug: "apple", logo: "/apple-logo-minimalist.png" },
  { id: "2", name: "Samsung", slug: "samsung", logo: "/samsung-logo.png" },
  { id: "3", name: "Google", slug: "google", logo: "/google-logo.png" },
  { id: "4", name: "OnePlus", slug: "oneplus", logo: "/oneplus-logo.jpg" },
  { id: "5", name: "Sony", slug: "sony", logo: "/sony-logo.png" },
]

export const mockCategories: Category[] = [
  { id: "1", name: "Smartphones", slug: "smartphones", productCount: 156 },
  { id: "2", name: "Laptops", slug: "laptops", productCount: 89 },
  { id: "3", name: "Tablets", slug: "tablets", productCount: 45 },
  { id: "4", name: "Audio", slug: "audio", productCount: 234 },
  { id: "5", name: "Wearables", slug: "wearables", productCount: 78 },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "iPhone 15 Pro Max 256GB Natural Titanium",
    slug: "iphone-15-pro-max-256gb-natural-titanium",
    description: "The most powerful iPhone ever with A17 Pro chip, titanium design, and the best camera system.",
    price: 179999,
    originalPrice: 189999,
    images: ["/iphone-15-pro-max-natural-titanium-front.jpg", "/iphone-15-pro-max-natural-titanium-back.jpg"],
    category: mockCategories[0],
    brand: mockBrands[0],
    variants: [
      { id: "v1", name: "Natural Titanium", type: "color", value: "#C4B8A4", priceModifier: 0, stock: 15 },
      { id: "v2", name: "Blue Titanium", type: "color", value: "#3B4F5C", priceModifier: 0, stock: 10 },
      { id: "v3", name: "256GB", type: "storage", value: "256GB", priceModifier: 0, stock: 25 },
      { id: "v4", name: "512GB", type: "storage", value: "512GB", priceModifier: 20000, stock: 12 },
    ],
    highlights: [
      "A17 Pro chip with 6-core GPU",
      "48MP Main camera with 5x optical zoom",
      "Titanium design",
      "USB-C with USB 3 speeds",
    ],
    specifications: {
      Display: "6.7-inch Super Retina XDR",
      Chip: "A17 Pro",
      Camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto",
      Battery: "Up to 29 hours video playback",
      Storage: "256GB",
    },
    stock: 25,
    sku: "IP15PM-256-NT",
    warranty: "1 Year Official Warranty",
    rating: 4.9,
    reviewCount: 1245,
    isFeatured: true,
    isNew: true,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-15",
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra 512GB Titanium Black",
    slug: "samsung-galaxy-s24-ultra-512gb-titanium-black",
    description: "The ultimate Galaxy experience with AI features, S Pen, and incredible camera system.",
    price: 159999,
    originalPrice: 174999,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: mockCategories[0],
    brand: mockBrands[1],
    variants: [
      { id: "v1", name: "Titanium Black", type: "color", value: "#1C1C1C", priceModifier: 0, stock: 20 },
      { id: "v2", name: "Titanium Gray", type: "color", value: "#6B6B6B", priceModifier: 0, stock: 15 },
      { id: "v3", name: "256GB", type: "storage", value: "256GB", priceModifier: -15000, stock: 18 },
      { id: "v4", name: "512GB", type: "storage", value: "512GB", priceModifier: 0, stock: 20 },
    ],
    highlights: ["Galaxy AI built-in", "200MP Camera with AI", "Titanium frame", "S Pen included"],
    specifications: {
      Display: "6.8-inch Dynamic AMOLED 2X",
      Chip: "Snapdragon 8 Gen 3",
      Camera: "200MP Main + 12MP Ultra Wide + 50MP Telephoto + 10MP Telephoto",
      Battery: "5000mAh",
      Storage: "512GB",
    },
    stock: 20,
    sku: "SGS24U-512-TB",
    warranty: "1 Year Official Warranty",
    rating: 4.8,
    reviewCount: 892,
    isFeatured: true,
    isNew: true,
    createdAt: "2024-01-20",
    updatedAt: "2024-01-20",
  },
  {
    id: "3",
    name: "MacBook Pro 14-inch M3 Pro 512GB Space Black",
    slug: "macbook-pro-14-m3-pro-512gb-space-black",
    description: "Supercharged by M3 Pro. Built for demanding workflows and intensive creative work.",
    price: 249999,
    originalPrice: 264999,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: mockCategories[1],
    brand: mockBrands[0],
    variants: [
      { id: "v1", name: "Space Black", type: "color", value: "#1D1D1F", priceModifier: 0, stock: 8 },
      { id: "v2", name: "Silver", type: "color", value: "#F5F5F7", priceModifier: 0, stock: 12 },
      { id: "v3", name: "512GB", type: "storage", value: "512GB", priceModifier: 0, stock: 15 },
      { id: "v4", name: "1TB", type: "storage", value: "1TB", priceModifier: 30000, stock: 5 },
    ],
    highlights: ["Apple M3 Pro chip", "18GB unified memory", "Liquid Retina XDR display", "Up to 17 hours battery"],
    specifications: {
      Display: "14.2-inch Liquid Retina XDR",
      Chip: "Apple M3 Pro",
      Memory: "18GB Unified Memory",
      Battery: "Up to 17 hours",
      Storage: "512GB SSD",
    },
    stock: 15,
    sku: "MBP14-M3P-512-SB",
    warranty: "1 Year Official Warranty",
    rating: 4.9,
    reviewCount: 567,
    isFeatured: true,
    isNew: false,
    createdAt: "2023-11-10",
    updatedAt: "2024-01-01",
  },
  {
    id: "4",
    name: "AirPods Pro (2nd Generation) with USB-C",
    slug: "airpods-pro-2nd-gen-usb-c",
    description: "Rebuilt from the sound up with H2 chip for smarter noise cancellation and immersive sound.",
    price: 34999,
    originalPrice: 39999,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: mockCategories[3],
    brand: mockBrands[0],
    variants: [],
    highlights: ["Active Noise Cancellation", "Adaptive Audio", "USB-C charging case", "Up to 6 hours battery"],
    specifications: {
      Chip: "H2",
      Battery: "Up to 6 hours listening time",
      "Case Battery": "Up to 30 hours total",
      Connectivity: "Bluetooth 5.3",
      Charging: "USB-C, MagSafe, Qi wireless",
    },
    stock: 50,
    sku: "APP2-USBC",
    warranty: "1 Year Official Warranty",
    rating: 4.8,
    reviewCount: 2341,
    isFeatured: true,
    isNew: false,
    createdAt: "2023-09-15",
    updatedAt: "2024-01-01",
  },
  {
    id: "5",
    name: "iPad Pro 12.9-inch M2 256GB Space Gray Wi-Fi",
    slug: "ipad-pro-12-9-m2-256gb-space-gray-wifi",
    description: "The ultimate iPad experience with M2 chip, stunning Liquid Retina XDR display, and all-day battery.",
    price: 139999,
    originalPrice: 149999,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: mockCategories[2],
    brand: mockBrands[0],
    variants: [
      { id: "v1", name: "Space Gray", type: "color", value: "#636366", priceModifier: 0, stock: 12 },
      { id: "v2", name: "Silver", type: "color", value: "#F5F5F7", priceModifier: 0, stock: 10 },
      { id: "v3", name: "256GB", type: "storage", value: "256GB", priceModifier: 0, stock: 18 },
      { id: "v4", name: "512GB", type: "storage", value: "512GB", priceModifier: 25000, stock: 8 },
    ],
    highlights: ["Apple M2 chip", "12.9-inch Liquid Retina XDR", "Pro camera system", "Face ID"],
    specifications: {
      Display: "12.9-inch Liquid Retina XDR",
      Chip: "Apple M2",
      Camera: "12MP Wide + 10MP Ultra Wide",
      Battery: "Up to 10 hours",
      Storage: "256GB",
    },
    stock: 18,
    sku: "IPADP129-M2-256-SG-W",
    warranty: "1 Year Official Warranty",
    rating: 4.7,
    reviewCount: 423,
    isFeatured: false,
    isNew: false,
    createdAt: "2023-06-01",
    updatedAt: "2024-01-01",
  },
  {
    id: "6",
    name: "Google Pixel 8 Pro 256GB Obsidian",
    slug: "google-pixel-8-pro-256gb-obsidian",
    description: "The best of Google with Tensor G3 chip, advanced AI features, and stunning camera capabilities.",
    price: 109999,
    originalPrice: 119999,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: mockCategories[0],
    brand: mockBrands[2],
    variants: [
      { id: "v1", name: "Obsidian", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 15 },
      { id: "v2", name: "Porcelain", type: "color", value: "#F5F5F5", priceModifier: 0, stock: 12 },
      { id: "v3", name: "128GB", type: "storage", value: "128GB", priceModifier: -10000, stock: 20 },
      { id: "v4", name: "256GB", type: "storage", value: "256GB", priceModifier: 0, stock: 15 },
    ],
    highlights: ["Google Tensor G3 chip", "50MP main camera with AI", "7 years of updates", "AI-powered features"],
    specifications: {
      Display: "6.7-inch LTPO OLED",
      Chip: "Google Tensor G3",
      Camera: "50MP Main + 48MP Ultra Wide + 48MP Telephoto",
      Battery: "5050mAh",
      Storage: "256GB",
    },
    stock: 15,
    sku: "GP8P-256-OB",
    warranty: "1 Year Official Warranty",
    rating: 4.6,
    reviewCount: 312,
    isFeatured: true,
    isNew: true,
    createdAt: "2024-01-05",
    updatedAt: "2024-01-05",
  },
  {
    id: "7",
    name: "Sony WH-1000XM5 Wireless Headphones Black",
    slug: "sony-wh-1000xm5-wireless-headphones-black",
    description: "Industry-leading noise cancellation with exceptional sound quality and all-day comfort.",
    price: 42999,
    originalPrice: 49999,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: mockCategories[3],
    brand: mockBrands[4],
    variants: [
      { id: "v1", name: "Black", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 25 },
      { id: "v2", name: "Silver", type: "color", value: "#C0C0C0", priceModifier: 0, stock: 20 },
    ],
    highlights: ["Industry-leading ANC", "30-hour battery life", "Premium comfort design", "Multipoint connection"],
    specifications: {
      Driver: "30mm",
      Battery: "Up to 30 hours",
      ANC: "HD Noise Cancelling Processor QN1",
      Connectivity: "Bluetooth 5.2",
      Weight: "250g",
    },
    stock: 25,
    sku: "SONYWH1000XM5-BK",
    warranty: "1 Year Official Warranty",
    rating: 4.9,
    reviewCount: 1567,
    isFeatured: false,
    isNew: false,
    createdAt: "2023-03-15",
    updatedAt: "2024-01-01",
  },
  {
    id: "8",
    name: "OnePlus 12 16GB/512GB Flowy Emerald",
    slug: "oneplus-12-16gb-512gb-flowy-emerald",
    description: "Flagship killer with Snapdragon 8 Gen 3, Hasselblad camera, and 100W SUPERVOOC charging.",
    price: 89999,
    originalPrice: 99999,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: mockCategories[0],
    brand: mockBrands[3],
    variants: [
      { id: "v1", name: "Flowy Emerald", type: "color", value: "#2E8B57", priceModifier: 0, stock: 18 },
      { id: "v2", name: "Silky Black", type: "color", value: "#1A1A1A", priceModifier: 0, stock: 22 },
      { id: "v3", name: "256GB", type: "storage", value: "256GB", priceModifier: -10000, stock: 25 },
      { id: "v4", name: "512GB", type: "storage", value: "512GB", priceModifier: 0, stock: 18 },
    ],
    highlights: ["Snapdragon 8 Gen 3", "Hasselblad Camera", "100W SUPERVOOC", "2K 120Hz Display"],
    specifications: {
      Display: "6.82-inch 2K LTPO AMOLED",
      Chip: "Snapdragon 8 Gen 3",
      Camera: "50MP Main + 64MP Periscope + 48MP Ultra Wide",
      Battery: "5400mAh",
      Storage: "512GB",
    },
    stock: 18,
    sku: "OP12-16-512-FE",
    warranty: "1 Year Official Warranty",
    rating: 4.7,
    reviewCount: 234,
    isFeatured: true,
    isNew: true,
    createdAt: "2024-01-25",
    updatedAt: "2024-01-25",
  },
  {
    id: "9",
    name: "Apple Watch Ultra 2 49mm Titanium with Orange Ocean Band",
    slug: "apple-watch-ultra-2-49mm-titanium-orange-ocean",
    description: "The most rugged and capable Apple Watch with precision dual-frequency GPS and Action button.",
    price: 109999,
    originalPrice: 119999,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: mockCategories[4],
    brand: mockBrands[0],
    variants: [
      { id: "v1", name: "Orange Ocean Band", type: "color", value: "#FF6B00", priceModifier: 0, stock: 10 },
      { id: "v2", name: "Blue Ocean Band", type: "color", value: "#0066CC", priceModifier: 0, stock: 8 },
    ],
    highlights: ["S9 SiP chip", "Titanium case", "100m water resistant", "36-hour battery life"],
    specifications: {
      Display: "49mm Always-On Retina",
      Chip: "S9 SiP",
      "Water Resistance": "100m",
      Battery: "Up to 36 hours",
      GPS: "Precision dual-frequency",
    },
    stock: 10,
    sku: "AWU2-49-TI-OOB",
    warranty: "1 Year Official Warranty",
    rating: 4.8,
    reviewCount: 189,
    isFeatured: false,
    isNew: false,
    createdAt: "2023-09-22",
    updatedAt: "2024-01-01",
  },
  {
    id: "10",
    name: "Samsung Galaxy Tab S9 Ultra 512GB Graphite Wi-Fi",
    slug: "samsung-galaxy-tab-s9-ultra-512gb-graphite-wifi",
    description: "The ultimate Android tablet with stunning 14.6-inch Dynamic AMOLED 2X display and S Pen.",
    price: 149999,
    originalPrice: 164999,
    images: ["/placeholder.svg?height=600&width=600", "/placeholder.svg?height=600&width=600"],
    category: mockCategories[2],
    brand: mockBrands[1],
    variants: [
      { id: "v1", name: "Graphite", type: "color", value: "#4A4A4A", priceModifier: 0, stock: 12 },
      { id: "v2", name: "Beige", type: "color", value: "#D4C5B5", priceModifier: 0, stock: 8 },
      { id: "v3", name: "256GB", type: "storage", value: "256GB", priceModifier: -20000, stock: 15 },
      { id: "v4", name: "512GB", type: "storage", value: "512GB", priceModifier: 0, stock: 12 },
    ],
    highlights: ["14.6-inch Dynamic AMOLED 2X", "Snapdragon 8 Gen 2", "S Pen included", "IP68 water resistant"],
    specifications: {
      Display: "14.6-inch Dynamic AMOLED 2X",
      Chip: "Snapdragon 8 Gen 2",
      Camera: "13MP Main + 8MP Ultra Wide",
      Battery: "11200mAh",
      Storage: "512GB",
    },
    stock: 12,
    sku: "SGTS9U-512-GR-W",
    warranty: "1 Year Official Warranty",
    rating: 4.6,
    reviewCount: 156,
    isFeatured: true,
    isNew: false,
    createdAt: "2023-08-11",
    updatedAt: "2024-01-01",
  },
]

export function getFeaturedProducts(): Product[] {
  return mockProducts.filter((p) => p.isFeatured)
}

export function getNewArrivals(): Product[] {
  return mockProducts.filter((p) => p.isNew)
}

export function getFlashSaleProducts(): Product[] {
  return mockProducts.filter((p) => p.originalPrice && p.originalPrice > p.price).slice(0, 5)
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return mockProducts.filter((p) => p.category.slug === categorySlug)
}

export function getProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug === slug)
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return mockProducts.filter((p) => p.category.slug === product.category.slug && p.id !== product.id).slice(0, limit)
}
